Resources:
  Microfrontend1Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: microfrontend1-bucket-ss
      # Add other bucket properties and configurations here...

  Microfrontend2Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: microfrontend2-bucket-ss
      # Add other bucket properties and configurations here...

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt Microfrontend1Bucket.WebsiteURL]]
            Id: Microfrontend1Origin
            S3OriginConfig: {}
          - DomainName: !Select [2, !Split ["/", !GetAtt Microfrontend2Bucket.WebsiteURL]]
            Id: Microfrontend2Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: Microfrontend1Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
