name: Microfrontend CI/CD Pipeline
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    paths:
      - '/infrastructure.yaml'

jobs:
  build-test-deploy-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: microfrontend1/src/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('microfrontend1/src/package-lock.json') }}

      - name: Install dependencies with npm
        run: |
          cd microfrontend1/src
          npm install        

      - name: Run tests with npm
        run: |
          cd microfrontend1/src
          npm test

      - name: Build microfrontends
        working-directory: microfrontend1/src
        run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MySessionName

      - name: Deploy microfrontends to S3 buckets
        run: |
          ls
          aws s3 sync ./microfrontend1/dist s3://microfrontend1-bucket
          aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"

      - name: Check if infrastructure.yaml has changed
        id: check_changes
        run: echo "Changes detected in infrastructure.yaml" && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"
        
      - name: Provision AWS infrastructure using CloudFormation
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          aws cloudformation deploy --template-file infrastructure.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
