name: Deploy Infrastructure
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if stack exists
        id: check_stack
        run: |
          stack_name="your-stack-name"
          aws cloudformation describe-stacks --stack-name $stack_name || echo "::set-output name=stack_exists::false"
          echo "::set-output name=stack_exists::true"

      - name: Deploy infrastructure.yaml
        if: steps.check_stack.outputs.stack_exists == 'false'
        run: |
          aws cloudformation create-stack --template-body file://.infrastructure/infrastructure.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
        id: create_stack

      - name: Wait for stack creation to complete
        if: steps.check_stack.outputs.stack_exists == 'false'
        run: |
          aws cloudformation wait stack-create-complete --stack-name your-stack-name

      - name: Update infrastructure.yaml
        if: steps.check_stack.outputs.stack_exists == 'true'
        run: |
          aws cloudformation update-stack --template-body file://.infrastructure/infrastructure.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
        id: update_stack

      - name: Wait for stack update to complete
        if: steps.check_stack.outputs.stack_exists == 'true'
        run: |
          aws cloudformation wait stack-update-complete --stack-name your-stack-name
